name: Build WALegacy Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang git perl build-essential curl

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Package
        run: |
          make package FINALPACKAGE=1

      - name: Upload Artifact (.deb)
        uses: actions/upload-artifact@v4
        with:
          name: WALegacy-Debian-Package
          path: packages/*.deb
