name: Build WALegacy Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        uses: anotherhadi/setup-theos@v1

      - name: Build Package
        run: |
          make package FINALPACKAGE=1

      - name: Upload Artifact (.deb)
        uses: actions/upload-artifact@v4
        with:
          name: WALegacy-Debian-Package
          path: packages/*.deb
